// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "OI.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "SmartDashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/ClimberExtended.h"
#include "Commands/ClimberRetract.h"
#include "Commands/DisplayShooterSpeed.h"
#include "Commands/GotoWall.h"
#include "Commands/PumpControl.h"
#include "Commands/SetShooterAngle.h"
#include "Commands/ShootDisk.h"
#include "Commands/Teleoperated.h"
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
OI::OI() 
{
	// Process operator interface input here.
   // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	driveJoystick = new Joystick(1);
	
	shootDiskButton = new JoystickButton(driveJoystick, 1);
	shootDiskButton->WhenPressed(new ShootDisk());
     
        // SmartDashboard Buttons
	SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
	SmartDashboard::PutData("Teleoperated", new Teleoperated());
	SmartDashboard::PutData("Pump Control", new PumpControl());
	SmartDashboard::PutData("Climber Extended", new ClimberExtended());
	SmartDashboard::PutData("Climber Retract", new ClimberRetract());
	SmartDashboard::PutData("Go to Wall", new GotoWall());
	SmartDashboard::PutData("Shoot Disk", new ShootDisk());
	SmartDashboard::PutData("Set Shooter Angle", new SetShooterAngle());
	SmartDashboard::PutData("Display Shooter Speed", new DisplayShooterSpeed());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
Joystick* OI::getDriveJoystick() {
	return driveJoystick;
}
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
