// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "RobotMap.h"
#include "LiveWindow/LiveWindow.h"
// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
Relay* RobotMap::frisbeeTransportFrisbeeTransportBelt = NULL;
Servo* RobotMap::frisbeeTransportDiskStopper1 = NULL;
Servo* RobotMap::frisbeeTransportDiskStopper2 = NULL;
SpeedController* RobotMap::drivetrainFrontRight = NULL;
SpeedController* RobotMap::drivetrainFrontLeft = NULL;
SpeedController* RobotMap::drivetrainBackRight = NULL;
SpeedController* RobotMap::drivetrainBackLeft = NULL;
RobotDrive* RobotMap::drivetrainHolonomic = NULL;
AnalogChannel* RobotMap::drivetrainUltrasonicFront = NULL;
AnalogChannel* RobotMap::drivetrainUltrasonicRear = NULL;
Relay* RobotMap::shooterFrisbeePusher = NULL;
GearTooth* RobotMap::shooterEncoder = NULL;
SpeedController* RobotMap::shooterMotor = NULL;
DigitalInput* RobotMap::shooterPusherStopSwitch = NULL;
SpeedController* RobotMap::shooterAngleAdjustVictor = NULL;
AnalogChannel* RobotMap::shooterAngleAdjustPotentiometer = NULL;
DigitalInput* RobotMap::shooterAngleLimitSwitch1 = NULL;
DigitalInput* RobotMap::shooterAngleLimitSwitch2 = NULL;
SpeedController* RobotMap::climberBeltMotor = NULL;
DoubleSolenoid* RobotMap::climberSolenoidLeft = NULL;
DoubleSolenoid* RobotMap::climberSolenoidRight = NULL;
DigitalInput* RobotMap::climberEngaged1 = NULL;
DigitalInput* RobotMap::climberEngaged2 = NULL;
Compressor* RobotMap::pumpCompressorPump = NULL;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=ALLOCATION
void RobotMap::init() {
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
	LiveWindow* lw = LiveWindow::GetInstance();
	frisbeeTransportFrisbeeTransportBelt = new Relay(1, 3);
	lw->AddActuator("Frisbee Transport", "Frisbee Transport Belt", frisbeeTransportFrisbeeTransportBelt);
	
	frisbeeTransportDiskStopper1 = new Servo(1, 7);
	lw->AddActuator("Frisbee Transport", "Disk Stopper 1", frisbeeTransportDiskStopper1);
	
	frisbeeTransportDiskStopper2 = new Servo(1, 8);
	lw->AddActuator("Frisbee Transport", "Disk Stopper 2", frisbeeTransportDiskStopper2);
	
	drivetrainFrontRight = new Talon(1, 1);
	lw->AddActuator("Drivetrain", "Front Right", (Talon*) drivetrainFrontRight);
	
	drivetrainFrontLeft = new Talon(1, 2);
	lw->AddActuator("Drivetrain", "Front Left", (Talon*) drivetrainFrontLeft);
	
	drivetrainBackRight = new Talon(1, 3);
	lw->AddActuator("Drivetrain", "Back Right", (Talon*) drivetrainBackRight);
	
	drivetrainBackLeft = new Talon(1, 4);
	lw->AddActuator("Drivetrain", "Back Left", (Talon*) drivetrainBackLeft);
	
	drivetrainHolonomic = new RobotDrive(drivetrainFrontLeft, drivetrainBackLeft,
              drivetrainFrontRight, drivetrainBackRight);
	
	drivetrainHolonomic->SetSafetyEnabled(false);
        drivetrainHolonomic->SetExpiration(0.1);
        drivetrainHolonomic->SetSensitivity(0.5);
        drivetrainHolonomic->SetMaxOutput(1.0);
        drivetrainHolonomic->SetInvertedMotor(RobotDrive::kFrontRightMotor, true);
        drivetrainHolonomic->SetInvertedMotor(RobotDrive::kRearRightMotor, true);
	drivetrainUltrasonicFront = new AnalogChannel(1, 1);
	lw->AddSensor("Drivetrain", "Ultrasonic Front", drivetrainUltrasonicFront);
	
	drivetrainUltrasonicRear = new AnalogChannel(1, 2);
	lw->AddSensor("Drivetrain", "Ultrasonic Rear", drivetrainUltrasonicRear);
	
	shooterFrisbeePusher = new Relay(1, 1);
	lw->AddActuator("Shooter", "Frisbee Pusher", shooterFrisbeePusher);
	
	shooterEncoder = new GearTooth(1, 1, false);
	lw->AddSensor("Shooter", "Encoder", shooterEncoder);
	
	shooterMotor = new Talon(1, 5);
	lw->AddActuator("Shooter", "Motor", (Talon*) shooterMotor);
	
	shooterPusherStopSwitch = new DigitalInput(1, 2);
	lw->AddSensor("Shooter", "Pusher Stop Switch", shooterPusherStopSwitch);
	
	shooterAngleAdjustVictor = new Victor(1, 9);
	lw->AddActuator("Shooter", "Angle Adjust Victor", (Victor*) shooterAngleAdjustVictor);
	
	shooterAngleAdjustPotentiometer = new AnalogChannel(1, 3);
	lw->AddSensor("Shooter", "Angle Adjust Potentiometer", shooterAngleAdjustPotentiometer);
	
	shooterAngleLimitSwitch1 = new DigitalInput(1, 5);
	lw->AddSensor("Shooter", "Angle Limit Switch 1", shooterAngleLimitSwitch1);
	
	shooterAngleLimitSwitch2 = new DigitalInput(1, 6);
	lw->AddSensor("Shooter", "Angle Limit Switch 2", shooterAngleLimitSwitch2);
	
	climberBeltMotor = new Talon(1, 6);
	lw->AddActuator("Climber", "Belt Motor", (Talon*) climberBeltMotor);
	
	climberSolenoidLeft = new DoubleSolenoid(1, 1, 2);      
	
	
	climberSolenoidRight = new DoubleSolenoid(1, 3, 4);      
	
	
	climberEngaged1 = new DigitalInput(1, 4);
	lw->AddSensor("Climber", "Engaged 1", climberEngaged1);
	
	climberEngaged2 = new DigitalInput(1, 7);
	lw->AddSensor("Climber", "Engaged 2", climberEngaged2);
	
	pumpCompressorPump = new Compressor(1, 8, 1, 2);
	
	
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}
