// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

#include "AutonomousRPMShootMiddleGoalHard.h"
#include "SetShooterAngle.h"

#define	AUTO_SHOOTER_SPEED						3000	// Placeholder

AutonomousRPMShootMiddleGoalHard::AutonomousRPMShootMiddleGoalHard() 
{
	// set the shooter angle
	AddSequential(new SetShooterAngle(300), 3.0);
	
	AddSequential(new SetShooterSpeed(AUTO_SHOOTER_SPEED, true), 3.0);

	AddSequential(new WaitCommand(AUTO_SHOOT_WAIT1));
	
	AddSequential(new FrisbeeShoot());
	
	AddSequential(new WaitCommand(AUTO_SHOOT_WAIT2));
	
	AddSequential(new FrisbeeShoot());
	
	AddSequential(new WaitCommand(AUTO_SHOOT_WAIT3));
	
	AddSequential(new FrisbeeShoot());

	AddSequential(new WaitCommand(AUTO_SHOOT_WAIT4));
	
	AddSequential(new FrisbeeShoot());
	
	AddSequential(new SetShooterSpeed(0.0, false));

}
