// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

#include "AutonomousRPMDriveForwardShoot.h"
#include "ChassisDriveDistanceStraight.h"
#include "ChassisDrivetoWallStraight.h"
#include "SetShooterSpeed.h"
#include "SetShooterAngle.h"
#include "FrisbeeShoot.h"

#define AUTO_DRIVE_POWER                  0.5
#define AUTO_DRIVE_TIME                   2.0

#define SHOOTER_WAIT                      0.0

#define SHOOTER_SPEED                  3000.0
#define SHOOTER_SPEED_TIMEOUT             3.0

#define SHOOTER_ANGLE                   653.0
#define SHOOTER_ANGLE_TIMEOUT             3.0

AutonomousRPMDriveForwardShoot::AutonomousRPMDriveForwardShoot() 
{
   // drive forward
	AddSequential(new ChassisDriveDistanceStraight(AUTO_DRIVE_TIME, AUTO_DRIVE_POWER));

	// set the shooter speed
	AddParallel(new SetShooterSpeed(SHOOTER_SPEED, true), SHOOTER_SPEED_TIMEOUT);
	
   // set the shooter angle
   AddSequential(new SetShooterAngle(SHOOTER_ANGLE), SHOOTER_ANGLE_TIMEOUT);
   
	// wait for the shooter to come up to speed
	AddSequential(new WaitCommand(SHOOTER_WAIT));
	
	// shoot the 1st Frisbee
	AddSequential(new FrisbeeShoot());
	
	// wait between shots
	AddSequential(new WaitCommand(SHOOTER_WAIT));
	
   // shoot the 2nd Frisbee
	AddSequential(new FrisbeeShoot());
	
   // wait between shots
	AddSequential(new WaitCommand(SHOOTER_WAIT));
	
   // shoot the 3rd Frisbee
	AddSequential(new FrisbeeShoot());

   // wait between shots
	AddSequential(new WaitCommand(SHOOTER_WAIT));
	
   // shoot the 4th Frisbee in case one misfired
	AddSequential(new FrisbeeShoot());
	
	// stop the shooter
	AddSequential(new SetShooterSpeed(0.0, false));
}
