// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#ifndef CHASSIS_DRIVE_DISTANCE_H
#define CHASSIS_DRIVE_DISTANCE_H
#define DRIVING_POWER               0.7
#define DRIVING_DIRECTION           0.0
#define DRIVING_ROTATION            0.0  
#define DRIVE_TIMER                 2.0

#include "Commands/Subsystem.h"
#include "../Robot.h"
#include "Timer.h" 

/**
 *
 *
 * @author ExampleAuthor
 */
class ChassisDriveDistance: public Command 
{
private:
   float driveDistance;
   Timer *timer;
   
public:
	ChassisDriveDistance(float distance);
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();
};

#endif
