// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "ChassisDrivetoWall.h"
#define STOPPING_DISTANCE          10.0f
#define DRIVE_POWER                 0.7
#define DRIVE_DIRECTION             0.0
#define DRIVE_ROTATION              0.0
ChassisDrivetoWall::ChassisDrivetoWall()
{
   // Use requires() here to declare subsystem dependencies
   // eg. requires(chassis);
   // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void ChassisDrivetoWall::Initialize() 
{
}
// Called repeatedly when this Command is scheduled to run
void ChassisDrivetoWall::Execute() 
{
   // drives motors
   Robot::drivetrain->HolonomicDrive(DRIVE_POWER, DRIVE_DIRECTION, DRIVE_ROTATION); 
}
// Make this return true when this Command no longer needs to run execute()
bool ChassisDrivetoWall::IsFinished()
{	
    // get the distance from the ultrasonic sensor
	distance = Robot::drivetrain->GetFrontDistance();
	
	// determine if the robot has reached the desired distance
	if (distance <= STOPPING_DISTANCE)
			return true;
	
	// loops until timer has run long enough
	return false;
}
// Called once after isFinished returns true
void ChassisDrivetoWall::End()
{
	// stops the drivetrain
	Robot::drivetrain->holonomic->StopMotor();
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void ChassisDrivetoWall::Interrupted()
{
   End();
}
