// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

#ifndef CLIMB_H
#define CLIMB_H

#include "Commands/CommandGroup.h"
#include "ClimberExtend.h"
#include "ClimberRetract.h"
#include "HookDowntoLimit.h"
#include "HookUptoEngage.h"

/**
 * This is a command group that allows the robot to climb.
 * 
 * @author HVA Robotics Team 3824
 */
class Climb: public CommandGroup {
public:	
	Climb();
};

#endif
