// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.



#ifndef CYPRESS_GOTO_POSITION_H
#define CYPRESS_GOTO_POSITION_H

#include "WPILib.h"
#include "../OI.h"
#include "SetShooterAngle.h"
#include "SetShooterSpeed.h"

#include "Commands/CommandGroup.h"

/**
 *
 *
 * @author ExampleAuthor
 */
class CypressGotoPosition: public CommandGroup 
{
private:
	double m_angle;
	double m_velocity;
	double m_isRPM;
public:	
	CypressGotoPosition();
	CypressGotoPosition(double angle, double velocity, bool isRPM = true);
	void Initialize();
	void End();
	void Interrupted();
};

#endif
