// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.


#include "FrisbeeAim.h"
#include <math.h>
FrisbeeAim::FrisbeeAim(double pixels) {
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::drivetrain);
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	PIDcontroller = new PIDController(
		SmartDashboard::GetNumber("Shooter Aim P: "),
		SmartDashboard::GetNumber("Shooter Aim I: "),
		SmartDashboard::GetNumber("Shooter Aim D: "),
		Robot::

	// remember the pixels
	pixelsToMove = pixels;
		
}

// Called just before this Command runs the first time
void FrisbeeAim::Initialize() {
	// starts PID controller
	PIDcontroller->Enable();
}

// Called repeatedly when this Command is scheduled to run
void FrisbeeAim::Execute() {
	
}

// Make this return true when this Command no longer needs to run execute()
bool FrisbeeAim::IsFinished() {
	return false;
}

// Called once after isFinished returns true
void FrisbeeAim::End() {
	PIDcontroller->Disable();	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void FrisbeeAim::Interrupted() {
	End();
}
