// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

#ifndef FRISBEE_SHOOT_H
#define FRISBEE_SHOOT_H

#include "Timer.h"
#include "Commands/Subsystem.h"
#include "../Robot.h"

/**
 *
 *
 * @author HVA Robotics Team 3824
 */
class FrisbeeShoot: public Command 
{
private:
	Timer *m_pusherTimer;
	bool m_isJammed;
public:
	FrisbeeShoot();
	virtual void Initialize();
	virtual void Execute();
	virtual bool IsFinished();
	virtual void End();
	virtual void Interrupted();

	static int lastShotDataCounter;
};

#endif
