// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

#include "SetShooterAngle.h"
#include "FrisbeeAimAndShoot.h"
#include "FrisbeeShoot.h"
#include "SetShooterSpeed.h"
#include "FrisbeeAim.h"
FrisbeeAimAndShoot::FrisbeeAimAndShoot()
{
	// Add Commands here:
	// e.g. AddSequential(new Command1());
	//      AddSequential(new Command2());
	// these will run in order.
   
   // To run multiple commands at the same time,
   // use AddParallel()
   // e.g. AddParallel(new Command1());
   //      AddSequential(new Command2());
   // Command1 and Command2 will run in parallel.
  
   //AddSequential(new SetShooterAngle(FRISBEE_ANGLE_AUTO));
   //AddSequential(new FrisbeeAim());

   float shooterSpeed = SmartDashboard::GetNumber("Shooter Voltage:");
   
   // sets speed of the shooter to the voltage read in from user
   AddSequential(new SetShooterSpeed(shooterSpeed));
   
   // shoots one frisbee
   AddSequential(new FrisbeeShoot());
}
