// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

#ifndef FRISBEE_AIM_AND_SHOOT_H
#define FRISBEE_AIM_AND_SHOOT_H

// The 5.0 is a placeholder. This shall come from image processing 
// calculations. 					

#define FRISBEE_ANGLE_AUTO			5.0		

#include "Commands/CommandGroup.h"

/**
 * This is a commmand group for aiming and firing a frisbee.
 * The only places this is called is in the Autonomous commands.
 * 
 * Pulls a float from the SmartDashboard and inputs it to the 
 * SetShooterSpeed command, which is supposed to set the speed of the wheel
 * to the float shooterSpeed.
 * 
 * TODO: Aiming isn't implemented yet.
 *
 * @author HVA Robotics Team 3824
 */
class FrisbeeAimAndShoot: public CommandGroup 
{
public:	
	FrisbeeAimAndShoot();
};

#endif
