// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "SetShooterAngle.h"
SetShooterAngle::SetShooterAngle(double setPoint) 
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooterAngleAdjust);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	
	// remember the desired setpoint
	angleSetPoint = setPoint;
}
// Called just before this Command runs the first time
void SetShooterAngle::Initialize() 
{
   Robot::shooterAngleAdjust->SetSetpoint(angleSetPoint);
}
// Called repeatedly when this Command is scheduled to run
void SetShooterAngle::Execute() 
{
	
}
// Make this return true when this Command no longer needs to run execute()
bool SetShooterAngle::IsFinished() 
{
   return Robot::shooterAngleAdjust->OnTarget();
}
// Called once after isFinished returns true
void SetShooterAngle::End() 
{
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SetShooterAngle::Interrupted() 
{
}
