// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "SetShooterSpeed.h"
SetShooterSpeed::SetShooterSpeed(double speed) 
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::shooterWheel);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	shooterSpeed = speed;
	shooterTimer = new Timer();
}
// Called just before this Command runs the first time
void SetShooterSpeed::Initialize() 
{
   shooterTimer->Reset();
   shooterTimer->Start();
	Robot::shooterWheel->SetWheelSpeed(shooterSpeed);
}
// Called repeatedly when this Command is scheduled to run
void SetShooterSpeed::Execute() 
{
	
}
// Make this return true when this Command no longer needs to run execute()
bool SetShooterSpeed::IsFinished() 
{
	return shooterTimer->Get() > 3.0;
}
// Called once after isFinished returns true
void SetShooterSpeed::End() 
{
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void SetShooterSpeed::Interrupted()
{
}
