// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

#include "ShootHangingonTower.h"
#include "SetShooterSpeed.h"
#include "SetShooterAngle.h"

ShootHangingonTower::ShootHangingonTower()
{
	// disable the shooter
	AddParallel(new SetShooterSpeed(HANGING_ON_TOWER_VELOCITY, HANGING_ON_TOWER_IS_RPM), 3.0);
	
	// set the shooter angle
	AddParallel(new SetShooterAngle(HANGING_ON_TOWER_ANGLE), 3.0);	
}
