// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

#include "TestDriveStraight.h"
#include "ChassisDriveDistanceStraight.h"

#define POWER 0.4

TestDriveStraight::TestDriveStraight() 
{
	for (int index = 0; index < 10; index++)
	{
	   // drive straight to get the first Frisbee
	   AddSequential(new ChassisDriveDistanceStraight(0.35, POWER), 3.0);

	   // wait to allow the robot to move under the tower
	   AddSequential(new WaitCommand(10.0));
    }

//	   // drive straight to get the first Frisbee
//	   AddSequential(new ChassisDriveDistanceStraight(0.2, POWER), 3.0);
//
//	   // wait to allow the robot to move under the tower
//	   AddSequential(new WaitCommand(10.0));
//	   
//	   // drive straight to get the first Frisbee
//	   AddSequential(new ChassisDriveDistanceStraight(0.3, POWER), 3.0);
//
//	   // wait to allow the robot to move under the tower
//	   AddSequential(new WaitCommand(10.0));
//	   
//	   // drive straight to get the first Frisbee
//	   AddSequential(new ChassisDriveDistanceStraight(0.4, POWER), 3.0);
//
//	   // wait to allow the robot to move under the tower
//	   AddSequential(new WaitCommand(10.0));
//	   
//	   // drive straight to get the first Frisbee
//	   AddSequential(new ChassisDriveDistanceStraight(0.5, POWER), 3.0);
//
//	   // wait to allow the robot to move under the tower
//	   AddSequential(new WaitCommand(10.0));
//	   
//	   // drive straight to get the first Frisbee
//	   AddSequential(new ChassisDriveDistanceStraight(0.6, POWER), 3.0);
}
