// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#include "UpdateShooterPID.h"
UpdateShooterPID::UpdateShooterPID()
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	Requires(Robot::pickup);
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}
// Called just before this Command runs the first time
void UpdateShooterPID::Initialize() 
{
	Robot::shooterWheel->getPIDController()->SetPID(
	        SmartDashboard::GetNumber("Shooter Speed P Term") / 1000.0,
			  SmartDashboard::GetNumber("Shooter Speed I Term") / 1000.0, 
			  SmartDashboard::GetNumber("Shooter Speed D Term") / 1000.0);
	Robot::shooterAngleAdjust->getPIDController()->SetPID(
	      SmartDashboard::GetNumber("Shooter Angle P Term"),
			SmartDashboard::GetNumber("Shooter Angle I Term"),
			SmartDashboard::GetNumber("Shooter Angle D Term"));
}
// Called repeatedly when this Command is scheduled to run
void UpdateShooterPID::Execute()
{
	
}
// Make this return true when this Command no longer needs to run execute()
bool UpdateShooterPID::IsFinished() 
{
	return true;
}
// Called once after isFinished returns true
void UpdateShooterPID::End() 
{
	
}
// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void UpdateShooterPID::Interrupted() 
{
}
