// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.

#include "UpdatePIDTerms.h"

UpdatePIDTerms::UpdatePIDTerms() 
{
	// Use requires() here to declare subsystem dependencies
	// eg. requires(chassis);
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
	// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
}

// Called just before this Command runs the first time
void UpdatePIDTerms::Initialize()
{
   Robot::shooterWheel->getPIDController()->SetPID(
         SmartDashboard::GetNumber("Shooter Speed P Term"),
         SmartDashboard::GetNumber("Shooter Speed I Term"), 
         SmartDashboard::GetNumber("Shooter Speed D Term"));
   Robot::shooterAngleAdjust->getPIDController()->SetPID(
         SmartDashboard::GetNumber("Shooter Angle P Term"),
         SmartDashboard::GetNumber("Shooter Angle I Term"),
         SmartDashboard::GetNumber("Shooter Angle D Term"));
   Robot::pickup->getPIDController()->SetPID(
         SmartDashboard::GetNumber("Pickup P Term"),
         SmartDashboard::GetNumber("Pickup I Term"),
         SmartDashboard::GetNumber("Pickup D Term"));
}

// Called repeatedly when this Command is scheduled to run
void UpdatePIDTerms::Execute()
{
	
}

// Make this return true when this Command no longer needs to run execute()
bool UpdatePIDTerms::IsFinished() 
{
	return false;
}

// Called once after isFinished returns true
void UpdatePIDTerms::End()
{
	
}

// Called when another command which requires one or more of the same
// subsystems is scheduled to run
void UpdatePIDTerms::Interrupted()
{

}
