// RobotBuilder Version: 0.0.2
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in th future.
#ifndef SHOOTER_ANGLE_ADJUST_H
#define SHOOTER_ANGLE_ADJUST_H
#include "Commands/PIDSubsystem.h"
#include "WPILib.h"
/**
 *
 *
 * @author ExampleAuthor
 */
class ShooterAngleAdjust: public PIDSubsystem 
{
 public:
	// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	SpeedController* motor;
	AnalogChannel* potentiometer;
	DigitalInput* limitSwitchHigh;
	DigitalInput* limitSwitchLow;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
	ShooterAngleAdjust();
	double ReturnPIDInput();
	void UsePIDOutput(double output);
	void InitDefaultCommand();
	
	double targeAdjustValue;
	
	void setAngleAdjustValue(double value) 
	{
		targeAdjustValue = value;
	}
	
};
#endif
